### PR TITLE
README.md of Bootstrap created

### LINKED ISSUE #18: Add Bootstrap Template and Documentation
**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

**Current behavior:**

There is no template starter and documentation mentioned in the repository.
**Expected behavior:**

A template starter and a quick tutorial would be provided for the users.
**Other information:**

### PR DESCRIPTION
**Pull request by ghost**
I have created the documentation for the bootstrap template started tutorial.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Tests for the changes have been added (for new templates)
- [x] Docs have been reviewed and added/updated if needed (for new templates)

## Fixes issue  

 

Fixes: #18 

## Pull request type

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?
 There was no documentation for the Bootstrap template starter.

- There was no documentation for the Bootstrap template starter.
- No pre-reqs were provided.

## What is the new behavior?

- Added the documentation for Bootstrap
- Added the necessary pre-requisites needed for the same.

## Other information

None

### CODE REVIEW

**Comment by waterupto** [comment]
I have been trying for the past few hours, but every time when I edit the README.md it comes up with a new issue. 
There are 4 issues that I am not able to do. Please help me with it.

**Comment by waterupto** [comment]
I tried a couple of times to resolve the issues, but not able to do so. Please help me with it.

**Comment by ghost** [comment]
Please review the PR of the documentation and let me know I can do something with it.

**Comment by ghost** [comment]
Sir, any update on this?

**Comment by harsh-2711** [comment]
@waterupto The contents of the `README` file LGTM but please solve the codacy issues.

**Comment by ghost** [comment]
I have been trying to solve it, but every time it shows the same problem. Can you please help me with it?

**Comment by harsh-2711** [comment]
@waterupto You need to remove extra spaces and indentations everywhere. The main issue is you are using different indentations for the same list items.

**Comment by ghost** [comment]
Done @harsh-2711

**Comment by harsh-2711** [comment]
@waterupto There's some issue in bulleting in the file. Also, you are missing some header guidelines. Please check the `README` file of spring boot for more details. Also, look for which topics are we including in the main technology level `README` file and do the changes accordingly.

**Comment by ghost** [comment]
I saw the spring-boot `README` file and have made it according to that only. I have corrected the bulleting issues and made other necessary changes as well. I don't see any topics missing now. 
> @waterupto There's some issue in bulleting in the file. Also, you are missing some header guidelines. Please check the `README` file of spring boot for more details. Also, look for which topics are we including in the main technology level `README` file and do the changes accordingly.

**Comment by ghost** [comment]
Sir, I have been working on this single thing for the past 10 days. I know my initial efforts were not up to the mark, but if you can please get this merged and let me proceed further.

**Comment by harsh-2711** [comment]
@waterupto Unless everything is perfect I can't merge things. You can surely work on multiple issues at once and we will review all of them in parallel if you are thinking that it's taking too long. This is your first PR and it takes time to get used to the contributors' guidelines.

**Comment by harsh-2711** [comment]
@waterupto I can still see many issues in your PR. This time, I'll solve all of them so that you can see what's missing and will then merge it. But from next time, please take care of it.

**Comment by ghost** [comment]
Sure sir, thank you.

**Comment by harsh-2711** [comment]
@waterupto Thanks for the PR

**Comment by harsh-2711** [comment]
give @waterupto 25 points

**Comment by harsh-2711** [comment]
@all-contributors bot please add @waterupto for docs

**Pull request merged**
